"use client";
import React, { createContext, useState, useContext } from 'react';

// Dictionary for translations
const translations = {
  en: {
    // Header
    searchPlaceholder: "Search student names or lessons...",
    searchInsights: "Search insights...",
    
    // Sidebar
    appName: "Smart Learning",
    appSubtitle: "AI Assistant",
    navHome: "Home",
    navStudents: "Students",
    navAnalytics: "Analytics",
    navInterventions: "Interventions",
    navTimeline: "Timeline",
    navSettings: "Settings",
    newAnalysis: "New Analysis",

    // Dashboard
    goodMorning: "Good Morning, Sarah!",
    dashboardDesc: "Your AI Assistant has identified 3 key opportunities for student growth today. Ready to dive into the morning insights?",
    viewMorningBriefing: "View Morning Briefing",
    activityLogs: "Activity Logs",
    dailyAttendance: "Daily Attendance",
    responseRate: "Response Rate",
    classroomMood: "Classroom Mood",
    riskAlerts: "Risk Alerts",
    stable: "Stable",
    high: "High",
    alert: "Alert",
    cheerful: "Cheerful",
    weeklyProgress: "Weekly Progress Chart",
    weeklyProgressDesc: "Average student mastery across all subjects",
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", today: "Today",
    aiRecommendations: "AI Recommendations",
    diffContent: "Differentiated Content",
    geomGroupBridge: "Geometry Group Bridge",
    geomDesc: "5 students are struggling with 'Angles'. Try the 'Protractor Sandbox' activity.",
    assignTask: "Assign Task",
    motivationBoost: "Motivation Boost",
    encouragementNeeded: "Encouragement Needed",
    encouragementDesc: "Leo M. has finished 3 assignments early. A small shoutout could boost engagement.",
    sendNote: "Send Note",

    // Student Monitoring
    studentMonitoringTitle: "Student Monitoring",
    studentMonitoringDesc: "Real-time classroom response tracking. Select a student to view detailed AI-generated progress reports and recommended interventions.",
    gradeLabel: "Grade:",
    allGrades: "All Grades",
    grade4: "Grade 4",
    grade5: "Grade 5",
    riskLabel: "Risk:",
    anyStatus: "Any Status",
    struggling: "Struggling",
    developing: "Developing",
    onTrack: "On Track",
    geometryMastery: "Geometry Mastery",
    latestScore: "Latest Score",
    status: "Status",
    mastered: "Mastered",
    interventionsBtn: "Interventions",
    viewProfileBtn: "View Profile",
    algebraicEquations: "Algebraic Equations",
    aiAlert: "AI Alert",
    needsSupport: "Needs Support",
    quickHelpBtn: "Quick Help",
    profileBtn: "Profile",
    fractionsRatios: "Fractions & Ratios",
    trend: "Trend",
    improving: "Improving",
    historyBtn: "History",
    calculusIntro: "Calculus Intro",
    addStudent: "Add Student",
    enrollLearner: "Enroll a new learner",
    aiClassInsight: "AI Classroom Insight",
    aiClassInsightDesc: "Based on current response data, 14% of the class is finding the 'Polynomials' topic challenging. We recommend a 15-minute bridge session to clarify base concepts before the next module.",
    generateLessonPlan: "Generate Lesson Plan",

    // Analytics
    analyticsTitle: "Deep-Dive Analytics",
    analyticsDesc: "Understanding student comprehension and identifying intervention opportunities with AI-driven insights.",
    classMastery: "Class-wide Concept Mastery",
    classMasteryDesc: "Real-time lesson comprehension across all learning modules.",
    highMastery: "High Mastery",
    inProgress: "In Progress",
    interventionNeeded: "Intervention Needed",
    engagementPulse: "Engagement Pulse",
    classInteractivity: "Class interactivity trends.",
    insight: "Insight",
    insightDesc: "Engagement peaked during the 'Cell Division' simulation.",
    detailedTrend: "Detailed Trend Analytics",
    topicPerformance: "Topic-wise performance over the semester.",
    molBiology: "Molecular Biology",
    geneticsBasics: "Genetics Basics",
    ecologySystems: "Ecology & Systems",
    dataAnalysis: "Data Analysis Labs",
    interventionSuccess: "Intervention Success Rate",
    trackingRecovery: "Tracking student recovery after AI prompts.",
    success: "Success",
    studentsRecovered: "12 Students recovered",
    thisWeekInc: "+14% this week",
    pendingIntervention: "4 Pending intervention",
    actNow: "Act Now",
    aiRecEngine: "AI Recommendation Engine",
    aiRecEngineDesc: "The AI has identified a specific comprehension gap in 'Genetic Sequencing' for 15% of the class. It recommends a 10-minute visual review session before the next lab.",
    generateSlides: "Generate Review Slides",
    dismissInsight: "Dismiss Insight",

    // Intervention Hub
    interventionHubTitle: "Intervention Hub",
    interventionHubDesc: "AI-generated recommendations to support your students' growth based on recent performance data.",
    filterBtn: "Filter",
    exportReportBtn: "Export Report",
    targetedInterventions: "Targeted Interventions",
    newInsightsCount: "4 New Insights",
    groupA: "Group A: Fractions Mastery",
    urgent: "Urgent",
    groupADesc: "5 students are struggling with improper fractions. Recommendation: Schedule a 15-minute small group review focused on visual pie models.",
    assignedToGroup: "Assigned to Group A",
    individualMia: "Individual: Mia Chen",
    moderate: "Moderate",
    individualMiaDesc: "Mia has missed the last two quizzes on Algebraic Equations. Recommendation: Assign 1-on-1 tutoring session.",
    assignSessionBtn: "Assign Session",
    interventionHistory: "Intervention History",
    interventionHistoryDesc: "See how past interventions have impacted student performance.",
    visualCues: "Visual Reading Cues",
    visualCuesDesc: "Applied to 3 students last week.",
    scoreIncrease: "+15% avg score increase",
    extraMath: "Extra Math Homework",
    extraMathDesc: "Applied to Group B 2 weeks ago.",
    noChange: "No significant change",

    // Timeline
    timelineTitle: "Activity Timeline",
    timelineDesc: "Track AI insights, system alerts, and your recent actions across all classes.",
    filterAll: "All Activity",
    filterAI: "AI Insights",
    filterAlerts: "Alerts",
    filterActions: "My Actions",
    logAiInsight: "AI detected a comprehension gap in Molecular Biology for 5 students.",
    logTeacherAction: "You sent a motivational note to Mia Chen.",
    logSystemAlert: "Class attendance dropped below 90% today.",
    logAiRec: "AI recommended a 15-minute visual review session.",
    logTeacherAction2: "You assigned 'Fractions Practice' to Group A.",

    // Input Score
    inputScoreTitle: "Input Student Scores",
    inputScoreDesc: "Enter recent quiz or assignment scores. The AI will automatically analyze these to update learning gaps.",
    selectClass: "Select Class",
    selectSubject: "Select Subject",
    selectTopic: "Select Topic",
    studentName: "Student Name",
    score: "Score (0-100)",
    notes: "Optional Notes",
    saveScores: "Save & Analyze Scores",
    uploadExcelBtn: "Upload Excel CSV",
    manualInputTab: "Manual Input",
    importDataTab: "Import Data",
    uploadDesc: "Drag and drop your Excel or CSV file here, or click to browse. The system will automatically map the names and scores.",

    // Login
    loginTitle: "Welcome Back",
    loginDesc: "Enter your credentials to access your account.",
    imATeacher: "I'm a Teacher",
    imAStudent: "I'm a Student",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot password?",
    loginBtn: "Sign In",

    // Add Student
    addStudentTitle: "Enroll New Student",
    addStudentDesc: "Create an account for a new student to give them access to the learning portal.",
    fullName: "Full Name",
    parentEmail: "Parent/Guardian Phone Number",
    studentEmail: "Student Email (Gmail)",
    createPassword: "Create Password",
    generatePassword: "Auto-generate",
    enrollBtn: "Enroll Student",

    // Student Dashboard
    studentDashWelcome: "Hi Mia! You have 1 special mission today.",
    studentDashDesc: "Your teacher has prepared a fun challenge to help you master Fractions.",
    startMission: "Start Mission",
    myProgress: "My Progress",
    missionCompleted: "Mission Completed!",
    keepItUp: "Keep it up! You're doing great.",
  },
  id: {
    // Header
    searchPlaceholder: "Cari nama siswa atau pelajaran...",
    searchInsights: "Cari wawasan...",
    
    // Sidebar
    appName: "Belajar Pintar",
    appSubtitle: "Asisten AI",
    navHome: "Beranda",
    navStudents: "Siswa",
    navAnalytics: "Analitik",
    navInterventions: "Intervensi",
    navTimeline: "Linimasa",
    navSettings: "Pengaturan",
    newAnalysis: "Analisis Baru",

    // Dashboard
    goodMorning: "Selamat Pagi, Sarah!",
    dashboardDesc: "Asisten AI Anda telah mengidentifikasi 3 peluang utama untuk perkembangan siswa hari ini. Siap untuk menyelami wawasan pagi ini?",
    viewMorningBriefing: "Lihat Ringkasan Pagi",
    activityLogs: "Log Aktivitas",
    dailyAttendance: "Kehadiran Harian",
    responseRate: "Tingkat Respon",
    classroomMood: "Suasana Kelas",
    riskAlerts: "Peringatan Risiko",
    stable: "Stabil",
    high: "Tinggi",
    alert: "Siaga",
    cheerful: "Ceria",
    weeklyProgress: "Grafik Perkembangan Mingguan",
    weeklyProgressDesc: "Rata-rata penguasaan siswa di semua mata pelajaran",
    last7Days: "7 Hari Terakhir",
    last30Days: "30 Hari Terakhir",
    mon: "Sen", tue: "Sel", wed: "Rab", thu: "Kam", fri: "Jum", today: "Hari Ini",
    aiRecommendations: "Rekomendasi AI",
    diffContent: "Konten Diferensiasi",
    geomGroupBridge: "Jembatan Kelompok Geometri",
    geomDesc: "5 siswa kesulitan dengan 'Sudut'. Coba aktivitas 'Kotak Pasir Busur Derajat'.",
    assignTask: "Beri Tugas",
    motivationBoost: "Dorongan Motivasi",
    encouragementNeeded: "Butuh Semangat",
    encouragementDesc: "Leo M. telah menyelesaikan 3 tugas lebih awal. Sedikit pujian bisa meningkatkan antusiasme.",
    sendNote: "Kirim Pesan",

    // Student Monitoring
    studentMonitoringTitle: "Pemantauan Siswa",
    studentMonitoringDesc: "Pelacakan respon kelas secara real-time. Pilih siswa untuk melihat laporan perkembangan dari AI dan rekomendasi intervensi detail.",
    gradeLabel: "Kelas:",
    allGrades: "Semua Kelas",
    grade4: "Kelas 4",
    grade5: "Kelas 5",
    riskLabel: "Risiko:",
    anyStatus: "Status Apa Pun",
    struggling: "Kesulitan",
    developing: "Berkembang",
    onTrack: "Sesuai Target",
    geometryMastery: "Penguasaan Geometri",
    latestScore: "Skor Terakhir",
    status: "Status",
    mastered: "Dikuasai",
    interventionsBtn: "Intervensi",
    viewProfileBtn: "Lihat Profil",
    algebraicEquations: "Persamaan Aljabar",
    aiAlert: "Peringatan AI",
    needsSupport: "Butuh Bantuan",
    quickHelpBtn: "Bantuan Cepat",
    profileBtn: "Profil",
    fractionsRatios: "Pecahan & Rasio",
    trend: "Tren",
    improving: "Meningkat",
    historyBtn: "Riwayat",
    calculusIntro: "Pengantar Kalkulus",
    addStudent: "Tambah Siswa",
    enrollLearner: "Daftarkan pelajar baru",
    aiClassInsight: "Wawasan Kelas AI",
    aiClassInsightDesc: "Berdasarkan data respon saat ini, 14% kelas merasa topik 'Polinomial' menantang. Kami merekomendasikan sesi jembatan 15 menit untuk memperjelas konsep dasar sebelum modul berikutnya.",
    generateLessonPlan: "Buat Rencana Pelajaran",

    // Analytics
    analyticsTitle: "Analisis Mendalam",
    analyticsDesc: "Memahami pemahaman siswa dan mengidentifikasi peluang intervensi dengan wawasan yang digerakkan oleh AI.",
    classMastery: "Penguasaan Konsep Kelas",
    classMasteryDesc: "Pemahaman pelajaran secara real-time di seluruh modul pembelajaran.",
    highMastery: "Penguasaan Tinggi",
    inProgress: "Sedang Berlangsung",
    interventionNeeded: "Butuh Intervensi",
    engagementPulse: "Denyut Keterlibatan",
    classInteractivity: "Tren interaktivitas kelas.",
    insight: "Wawasan",
    insightDesc: "Keterlibatan memuncak selama simulasi 'Pembelahan Sel'.",
    detailedTrend: "Analisis Tren Detail",
    topicPerformance: "Kinerja berdasarkan topik selama semester berjalan.",
    molBiology: "Biologi Molekuler",
    geneticsBasics: "Dasar-dasar Genetika",
    ecologySystems: "Ekologi & Sistem",
    dataAnalysis: "Lab Analisis Data",
    interventionSuccess: "Tingkat Keberhasilan Intervensi",
    trackingRecovery: "Melacak pemulihan siswa setelah arahan AI.",
    success: "Berhasil",
    studentsRecovered: "12 Siswa pulih",
    thisWeekInc: "+14% minggu ini",
    pendingIntervention: "4 Menunggu intervensi",
    actNow: "Tindak Sekarang",
    aiRecEngine: "Mesin Rekomendasi AI",
    aiRecEngineDesc: "AI telah mengidentifikasi celah pemahaman spesifik dalam 'Pengurutan Genetik' untuk 15% kelas. Merekomendasikan sesi ulasan visual 10 menit sebelum lab berikutnya.",
    generateSlides: "Buat Slide Ulasan",
    dismissInsight: "Abaikan Wawasan",

    // Intervention Hub
    interventionHubTitle: "Pusat Intervensi",
    interventionHubDesc: "Rekomendasi yang dihasilkan AI untuk mendukung pertumbuhan siswa Anda berdasarkan data kinerja terbaru.",
    filterBtn: "Saring",
    exportReportBtn: "Ekspor Laporan",
    targetedInterventions: "Intervensi Bertarget",
    newInsightsCount: "4 Wawasan Baru",
    groupA: "Grup A: Penguasaan Pecahan",
    urgent: "Mendesak",
    groupADesc: "5 siswa kesulitan dengan pecahan biasa. Rekomendasi: Jadwalkan ulasan kelompok kecil selama 15 menit yang difokuskan pada model pai visual.",
    assignedToGroup: "Ditugaskan ke Grup A",
    individualMia: "Individu: Mia Chen",
    moderate: "Sedang",
    individualMiaDesc: "Mia telah melewatkan dua kuis terakhir tentang Persamaan Aljabar. Rekomendasi: Tugaskan sesi bimbingan 1-on-1.",
    assignSessionBtn: "Beri Sesi",
    interventionHistory: "Riwayat Intervensi",
    interventionHistoryDesc: "Lihat bagaimana intervensi masa lalu berdampak pada kinerja siswa.",
    visualCues: "Isyarat Membaca Visual",
    visualCuesDesc: "Diterapkan ke 3 siswa minggu lalu.",
    scoreIncrease: "+15% peningkatan skor rata-rata",
    extraMath: "PR Matematika Ekstra",
    extraMathDesc: "Diterapkan ke Grup B 2 minggu lalu.",
    noChange: "Tidak ada perubahan signifikan",

    // Timeline
    timelineTitle: "Linimasa Aktivitas",
    timelineDesc: "Lacak wawasan AI, peringatan sistem, dan tindakan terbaru Anda di semua kelas.",
    filterAll: "Semua Aktivitas",
    filterAI: "Wawasan AI",
    filterAlerts: "Peringatan",
    filterActions: "Tindakan Saya",
    logAiInsight: "AI mendeteksi celah pemahaman pada Biologi Molekuler untuk 5 siswa.",
    logTeacherAction: "Anda mengirim pesan motivasi ke Mia Chen.",
    logSystemAlert: "Kehadiran kelas turun di bawah 90% hari ini.",
    logAiRec: "AI merekomendasikan sesi ulasan visual 15 menit.",
    logTeacherAction2: "Anda memberikan 'Latihan Pecahan' ke Grup A.",

    // Input Score
    inputScoreTitle: "Input Nilai Siswa",
    inputScoreDesc: "Masukkan nilai kuis atau tugas terbaru. AI akan menganalisisnya secara otomatis untuk memperbarui status penguasaan materi.",
    selectClass: "Pilih Kelas",
    selectSubject: "Pilih Mata Pelajaran",
    selectTopic: "Pilih Topik",
    studentName: "Nama Siswa",
    score: "Nilai (0-100)",
    notes: "Catatan (Opsional)",
    saveScores: "Simpan & Analisis Nilai",
    uploadExcelBtn: "Unggah CSV/Excel",
    manualInputTab: "Input Manual",
    importDataTab: "Impor Data",
    uploadDesc: "Tarik dan lepas file Excel atau CSV Anda di sini, atau klik untuk mencari. Sistem akan otomatis memetakan nama dan nilai.",

    // Login
    loginTitle: "Selamat Datang Kembali",
    loginDesc: "Masukkan kredensial Anda untuk mengakses akun.",
    imATeacher: "Saya Guru",
    imAStudent: "Saya Siswa",
    emailPlaceholder: "Alamat email",
    passwordPlaceholder: "Kata Sandi",
    forgotPassword: "Lupa kata sandi?",
    loginBtn: "Masuk",

    // Add Student
    addStudentTitle: "Daftarkan Siswa Baru",
    addStudentDesc: "Buat akun untuk siswa baru agar mereka bisa mengakses portal pembelajaran.",
    fullName: "Nama Lengkap",
    parentEmail: "No. WhatsApp Orang Tua/Wali",
    studentEmail: "Email Siswa (Gmail)",
    createPassword: "Buat Kata Sandi",
    generatePassword: "Buat Otomatis",
    enrollBtn: "Daftarkan Siswa",

    // Student Dashboard
    studentDashWelcome: "Hai Mia! Kamu punya 1 misi khusus hari ini.",
    studentDashDesc: "Gurumu telah menyiapkan tantangan seru untuk membantumu menguasai Pecahan.",
    startMission: "Mulai Misi",
    myProgress: "Perkembanganku",
    missionCompleted: "Misi Selesai!",
    keepItUp: "Teruskan! Kamu hebat.",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default language is English

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === 'en' ? 'id' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
